spring:
    thymeleaf:
        cache: false
        cache-period: 0
    template:
        cache: false
    datasource:
        name: springbootDB
        url: jdbc:mysql://104.225.148.124:3306/blog
        username: root
        password: qweasd
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20

mybatis:
    typeAliasesPackage: com.mawic.homepage.domain.model
    configuration:
        #logPrefix: "MYBATIS-LOG==>>>"
        logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
        mapUnderscoreToCamelCase: true


pagehelper:
    #默认值为false，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为true时，使用 RowBounds 分页会进行 count 查询。
    rowBoundsWithCount: true
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
